### ISSUE TITLE
Version 13 not loading on Jammy as specified in version chart

### ISSUE THREAD

**Issue by gamebox** [egor-tensin/setup-clang#10]
Attempting to use this in my CI workflow, and can't get v13 to load on Jammy.

Here is the build logs I see:

https://github.com/gamebox/chakra-lang/actions/runs/4148242687/jobs/7176032330

I don't know if this issue is temporary, but I would truly appreciate any pointers.

**Comment by egor-tensin** [comment]
Sorry, I don't think specifying the version as `13.0.0` is supported. Please try `13` as in the version table.

**Comment by gamebox** [comment]
That's totally a misunderstanding on my part.  Looks good with `13`.  Sorry about that, closing.
